blank_issues_enabled: true
contact_links:
    - name: zksync-developers Discussion
      url: https://github.com/ZKsync-Community-Hub/zkync-developers/discussions
      about: If you have any questions or need help beyond this project, please visit our Discussions page for zksync developers.
