import Head from 'next/head';
import { useEffect, useState } from 'react';
import { ConnectWalletTS } from '@/components/ConnectWalletTS';
import { ConnectWallet } from '@/components/ConnectWallet';
import { ShowConnectors } from '@/components/ShowConnectors';
import { ShowConnectorsTS } from '@/components/ShowConnectorsTS';
import { Account } from '@/components/Account';
import { AccountTS } from '@/components/AccountTS';
import { Balance } from '@/components/Balance';
import { BalanceTS } from '@/components/BalanceTS';
import { Block } from '@/components/Block';
import { BlockTS } from '@/components/BlockTS';
import { SendTx } from '@/components/SendTx';
import { SendTxTS } from '@/components/SendTxTS';
import { SendTxPrepared } from '@/components/SendTxPrepared';
import { SendTxPreparedTS } from '@/components/SendTxPreparedTS';
import { SignMessage } from '@/components/SignMessage';
import { SignMessageTS } from '@/components/SignMessageTS';
import { SignTypedData } from '@/components/SignTypedData';
import { SignTypedDataTS } from '@/components/SignTypedDataTS';
import { ReadContract } from '@/components/ReadContract';
import { ReadContractTS } from '@/components/ReadContractTS';
import { WriteContract } from '@/components/WriteContract';
import { WriteContractTS } from '@/components/WriteContractTS';

export default function Home() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <>
      <Head>
        <title>Wagmi ZKsync Demo</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div>
        <main>
          {mounted && (
            <>
              <ConnectWallet />
              <ConnectWalletTS />
              <ShowConnectors />
              <ShowConnectorsTS />
              <Account />
              <AccountTS />
              <Balance />
              <BalanceTS />
              <Block />
              <BlockTS />
              <SendTx />
              <SendTxTS />
              <SendTxPrepared />
              <SendTxPreparedTS />
              <SignMessage />
              <SignMessageTS />
              <SignTypedData />
              <SignTypedDataTS />
              <ReadContract />
              <ReadContractTS />
              <WriteContract />
              <WriteContractTS />
            </>
          )}
        </main>
      </div>
    </>
  );
}
