[package]
name = "sp1_program"
version = "0.1.0"
edition = "2021"

# ANCHOR: program-deps
[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "4.0.0-rc.3"
game-lib = { path = "../../game_lib" }
# ANCHOR_END: program-deps
