name: Test ZK Chain Tutorial

on: workflow_dispatch
  
jobs:
  zk-chain-test:
    # The playwright test will fail after 40 min, so this leaves some time for installations, etc.
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Install Dependencies
      run: bun install --frozen-lockfile
    - uses: actions/setup-node@v4
    - name: Install Playwright Browsers
      run: bun playwright install chromium --with-deps
    - name: Run test
      run: |
        export TERM=xterm-256color
        export COLUMNS=80
        export LINES=24
        xvfb-run bun test:headless tests/custom-zk-chain.spec.ts
