name: Test ZK Chain Tutorial

on: 
  workflow_dispatch:
  # TODO: remove this before merging
  pull_request:

  
jobs:
  zk-chain-test:
    # The playwright test will fail after 40 min, so this leaves some time for installations, etc.
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Install Dependencies
      run: bun install --frozen-lockfile
    - uses: actions/setup-node@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Install Yarn
      run: |
        npm install -g yarn
        yarn set version 1.22.19
    - name: Install Cargo tools
      run: |
        cargo install cargo-nextest
        cargo install sqlx-cli --version 0.8.1
    - name: Install Foundry ZKSync
      run: |
        curl -L https://raw.githubusercontent.com/matter-labs/foundry-zksync/main/install-foundry-zksync | bash
        source ~/.bashrc
        foundryup-zksync
    - name: Install ZKstack
      run: |
        curl -L https://raw.githubusercontent.com/matter-labs/zksync-era/main/zkstack_cli/zkstackup/install | bash
        zkstackup
    - name: Install Playwright Browsers
      run: bun playwright install chromium --with-deps
    - name: Run test
      run: |
        export TERM=xterm-256color
        export COLUMNS=80
        export LINES=24
        xvfb-run bun test:headless tests/custom-zk-chain.spec.ts
